name: Docker

on:
  push:
  pull_request:
  schedule:
    - cron: "17 3 * * *"

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        id: docker-login
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Docker Build and Push
        if: steps.docker-login.outcome == 'success'
        run: ./build.sh "--push"
      - name: Docker Build
        if: steps.docker-login.outcome == 'skipped'
        run: ./build.sh
